name: Deploy Angular to Strato

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: release-proj
        run: npm install

      - name: Build Angular app
        working-directory: release-proj
        run: npm run build -- --configuration production

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          local_path: ./release-proj/dist/release-proj/
          remote_path: /httpdocs/
